base: !include sets/base.yml
dodgecity: !include sets/dodgecity.yml
valleyofshadows: !include sets/valleyofshadows.yml
udolistinu: !include sets/udolistinu.yml
goldrush: !include sets/goldrush.yml
armedanddangerous: !include sets/armedanddangerous.yml
greattrainrobbery: !include sets/greattrainrobbery.yml
highnoon: !include sets/highnoon.yml
fistfulofcards: !include sets/fistfulofcards.yml
wildwestshow: !include sets/wildwestshow.yml
thebullet: !include sets/thebullet.yml
canyondiablo: !include sets/canyondiablo.yml