base: !include sets/base.yml
dodgecity: !include sets/dodgecity.yml
valleyofshadows: !include sets/valleyofshadows.yml
udolistinu: !include sets/udolistinu.yml
goldrush: !include sets/goldrush.yml
armedanddangerous: !include sets/armedanddangerous.yml
greattrainrobbery: !include sets/greattrainrobbery.yml
highnoon: !include sets/highnoon.yml
fistfulofcards: !include sets/fistfulofcards.yml
wildwestshow_characters: !include sets/wildwestshow_characters.yml
wildwestshow: !include sets/wildwestshow.yml
mostwanted: !include sets/mostwanted.yml
legends_basemod: !include sets/legends_basemod.yml
legends: !include sets/legends.yml
canyondiablo: !include sets/canyondiablo.yml
crazy_greygory: !include sets/crazy_greygory.yml
ghost_cards: {}
stickofdynamite: {}
shadowgunslingers: {}